let field = {},
printField = {}, //дополнительная переменная для блокс с текстом "печатает"
printFieldTxt = {},
textarea = {},
fieldBlock = [],
login = "",
p = [],
click = 0,
clickWhile = 0,
avatar = {};
